/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutSettings: typeof import('./../components/settings/AboutSettings.vue')['default']
    AdvancedConfigEditor: typeof import('./../components/library/AdvancedConfigEditor.vue')['default']
    CategoryManager: typeof import('./../components/library/CategoryManager.vue')['default']
    GameEditModal: typeof import('./../components/library/GameEditModal.vue')['default']
    GeneralSettings: typeof import('./../components/settings/GeneralSettings.vue')['default']
    IconSelector: typeof import('./../components/common/IconSelector.vue')['default']
    LanguageToggle: typeof import('./../components/common/LanguageToggle.vue')['default']
    LatencyChart: typeof import('./../components/dashboard/LatencyChart.vue')['default']
    LogsSettings: typeof import('./../components/settings/LogsSettings.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NetworkSettings: typeof import('./../components/settings/NetworkSettings.vue')['default']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NModalProvider: typeof import('naive-ui')['NModalProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NodeCard: typeof import('./../components/node/NodeCard.vue')['default']
    NodeEditModal: typeof import('./../components/node/NodeEditModal.vue')['default']
    NodeImportModal: typeof import('./../components/node/NodeImportModal.vue')['default']
    NodeManager: typeof import('./../components/node/NodeManager.vue')['default']
    NodeSelector: typeof import('./../components/dashboard/NodeSelector.vue')['default']
    NPopselect: typeof import('naive-ui')['NPopselect']
    NRadio: typeof import('naive-ui')['NRadio']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTag: typeof import('naive-ui')['NTag']
    ProcessSelector: typeof import('./../components/common/ProcessSelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsSidebar: typeof import('./../components/settings/SettingsSidebar.vue')['default']
    SubscriptionManagerModal: typeof import('./../components/node/SubscriptionManagerModal.vue')['default']
    ThemeToggle: typeof import('./../components/common/ThemeToggle.vue')['default']
  }
}
