/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutSettings: typeof import('./../components/settings/AboutSettings.vue')['default']
    CategoryManager: typeof import('./../components/library/CategoryManager.vue')['default']
    GameEditModal: typeof import('./../components/library/GameEditModal.vue')['default']
    GeneralSettings: typeof import('./../components/settings/GeneralSettings.vue')['default']
    IconSelector: typeof import('./../components/common/IconSelector.vue')['default']
    LanguageToggle: typeof import('./../components/common/LanguageToggle.vue')['default']
    LatencyChart: typeof import('./../components/dashboard/LatencyChart.vue')['default']
    LogsSettings: typeof import('./../components/settings/LogsSettings.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NetworkSettings: typeof import('./../components/settings/NetworkSettings.vue')['default']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NModalProvider: typeof import('naive-ui')['NModalProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NodeCard: typeof import('./../components/node/NodeCard.vue')['default']
    NodeEditModal: typeof import('./../components/node/NodeEditModal.vue')['default']
    NodeImportModal: typeof import('./../components/node/NodeImportModal.vue')['default']
    NodeManager: typeof import('./../components/node/NodeManager.vue')['default']
    NodeSelector: typeof import('./../components/dashboard/NodeSelector.vue')['default']
    NPopover: typeof import('naive-ui')['NPopover']
    NPopselect: typeof import('naive-ui')['NPopselect']
    NProgress: typeof import('naive-ui')['NProgress']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpin: typeof import('naive-ui')['NSpin']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTag: typeof import('naive-ui')['NTag']
    NTime: typeof import('naive-ui')['NTime']
    ProcessSelector: typeof import('./../components/common/ProcessSelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsSidebar: typeof import('./../components/settings/SettingsSidebar.vue')['default']
    SingboxInstallerGuard: typeof import('./../components/singbox/SingboxInstallerGuard.vue')['default']
    SubscriptionManagerModal: typeof import('./../components/node/SubscriptionManagerModal.vue')['default']
    ThemeToggle: typeof import('./../components/common/ThemeToggle.vue')['default']
  }
}
