/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdvancedConfigEditor: typeof import('./components/library/AdvancedConfigEditor.vue')['default']
    CategoryManager: typeof import('./components/library/CategoryManager.vue')['default']
    GameEditModal: typeof import('./components/library/GameEditModal.vue')['default']
    LatencyChart: typeof import('./components/dashboard/LatencyChart.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NModalProvider: typeof import('naive-ui')['NModalProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NodeCard: typeof import('./components/node/NodeCard.vue')['default']
    NodeEditModal: typeof import('./components/node/NodeEditModal.vue')['default']
    NodeImportModal: typeof import('./components/node/NodeImportModal.vue')['default']
    NodeManager: typeof import('./components/node/NodeManager.vue')['default']
    NodeSelector: typeof import('./components/node/NodeSelector.vue')['default']
    NRadio: typeof import('naive-ui')['NRadio']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeToggle: typeof import('./components/common/ThemeToggle.vue')['default']
  }
}
